name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        # This token is used to authenticate and should have enough permissions
        token: ${{ secrets.PUSH }}

    - name: Update README
      run: |
        if [ ! -f README.md ]; then
            echo "Creating README.md file..."
            touch README.md
        fi
        
        echo "Updated on $(date +"%Y-%m-%d")" >> README.md

    - name: Commit and push if changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add README.md
        git commit -m "Update README with date" || exit 0
        git push
